# Site settings
name: 薛  莲
location: 人事经理
company: 上海
position: 
github: https://sherry0520.github.io/
phone: 18516261826
email: 34106075@qq.com

# baseurl: "/sherry0520.github.io"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

